/*
 * FASS Design System — Clinical Edition
 * Paleta: Slate navy + white, acentos azul oscuro
 * Filosofía: limpio, serio, clínico — sin decoración superflua
 */

const C = {
  bg:        '#f1f5f9',
  surface:   '#ffffff',
  border:    '#e2e8f0',
  borderMd:  '#cbd5e1',
  text:      '#0f172a',
  textSub:   '#475569',
  textMuted: '#94a3b8',
  brand:     '#1d4ed8',
  brandDark: '#1e3a8a',
  danger:    '#b91c1c',
  dangerBg:  '#fef2f2',
  dangerBorder: '#fecaca',
  success:   '#15803d',
  successBg: '#f0fdf4',
  successBorder: '#bbf7d0',
  warning:   '#92400e',
  warningBg: '#fffbeb',
  warningBorder: '#fde68a',
  navy:      '#0f172a',
  navyHover: '#1e293b',
};

const font = '"Inter", system-ui, -apple-system, sans-serif';

const input = {
  width: '100%',
  padding: '9px 12px',
  borderRadius: '6px',
  border: `1px solid ${C.border}`,
  backgroundColor: C.surface,
  color: C.text,
  fontSize: '0.9rem',
  fontFamily: font,
  boxSizing: 'border-box',
  outline: 'none',
  transition: 'border-color 0.15s',
};

export const styles = {

  // ─── TIPOGRAFÍA ───────────────────────────────────────────────
  labelStyle: {
    color: C.text,
    fontSize: '0.8rem',
    fontFamily: font,
    fontWeight: '600',
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
  },
  labelStyleV2: {
    fontSize: '0.75rem',
    fontWeight: '600',
    color: C.textSub,
    marginBottom: '4px',
    fontFamily: font,
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
  },
  subLabel: {
    fontSize: '0.85rem',
    fontWeight: '600',
    color: C.text,
    marginBottom: '8px',
    fontFamily: font,
  },
  subLabelNormal: {
    fontSize: '0.875rem',
    color: C.text,
    fontWeight: '600',
    fontFamily: font,
  },
  secHeader: {
    fontSize: '0.7rem',
    color: C.brand,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    borderBottom: `1px solid ${C.border}`,
    marginBottom: '14px',
    paddingBottom: '6px',
    fontWeight: '700',
    fontFamily: font,
  },

  // ─── INPUTS ───────────────────────────────────────────────────
  inputStyle: { ...input, height: '38px', padding: '0 12px' },
  inputStyleV2: { ...input },
  selectStyle: {
    ...input,
    height: '38px',
    padding: '0 12px',
    cursor: 'pointer',
    appearance: 'none',
  },
  detailInput: {
    ...input,
    marginTop: '8px',
    minHeight: '60px',
    resize: 'vertical',
  },
  searchInput: {
    border: 'none',
    background: 'transparent',
    outline: 'none',
    width: '100%',
    color: C.text,
    fontFamily: font,
    fontSize: '0.9rem',
  },

  // ─── LAYOUT ───────────────────────────────────────────────────
  inputWrapper: { display: 'flex', flexDirection: 'column', gap: '6px', minWidth: '0' },
  calculatorLayout: { display: 'flex', gap: '24px', alignItems: 'flex-start' },
  asideStyle: { width: '380px', flexShrink: '0', position: 'sticky', top: '20px' },
  gridQuestions: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px 24px' },

  // ─── CABECERA ─────────────────────────────────────────────────
  headerStyle: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '0 32px',
    height: '56px',
    backgroundColor: C.navy,
    alignItems: 'center',
    borderBottom: `1px solid #1e293b`,
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },

  // ─── TARJETAS ─────────────────────────────────────────────────
  cardStyle: {
    backgroundColor: C.surface,
    padding: '24px',
    borderRadius: '8px',
    border: `1px solid ${C.border}`,
    marginBottom: '16px',
  },
  optionCard: {
    backgroundColor: C.surface,
    padding: '28px 24px',
    borderRadius: '8px',
    border: `1px solid ${C.border}`,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    transition: 'border-color 0.2s, box-shadow 0.2s',
  },
  cardTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '1rem',
    marginBottom: '16px',
    fontWeight: '700',
    color: C.text,
    fontFamily: font,
  },
  cardHeading: {
    color: C.text,
    fontWeight: '700',
    margin: '0 0 8px 0',
    fontSize: '1.05rem',
    fontFamily: font,
  },
  infoCard: {
    backgroundColor: C.surface,
    padding: '32px',
    borderRadius: '8px',
    border: `1px solid ${C.border}`,
    position: 'relative',
    marginBottom: '16px',
    fontFamily: font,
  },
  questionBlock: {
    padding: '14px',
    backgroundColor: '#fafafa',
    borderRadius: '6px',
    border: `1px solid ${C.border}`,
  },
  emptyCard: {
    padding: '48px',
    textAlign: 'center',
    color: C.textMuted,
    border: `1px dashed ${C.borderMd}`,
    borderRadius: '8px',
    backgroundColor: C.surface,
  },
  itemPacienteStyle: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 16px',
    backgroundColor: '#fafafa',
    borderRadius: '6px',
    border: `1px solid ${C.border}`,
    color: C.text,
    fontFamily: font,
  },
  searchBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    backgroundColor: C.surface,
    padding: '9px 14px',
    borderRadius: '6px',
    border: `1px solid ${C.border}`,
    color: C.text,
  },

  // ─── BOTONES ──────────────────────────────────────────────────
  startBtn: {
    padding: '9px 18px',
    backgroundColor: C.navy,
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.875rem',
    fontFamily: font,
  },
  backBtn: {
    background: 'none',
    border: 'none',
    color: C.brand,
    cursor: 'pointer',
    marginBottom: '12px',
    fontWeight: '600',
    fontSize: '0.875rem',
    fontFamily: font,
    padding: '0',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  logoutBtn: {
    background: 'none',
    border: `1px solid rgba(255,255,255,0.2)`,
    color: '#cbd5e1',
    cursor: 'pointer',
    fontWeight: '500',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '0.85rem',
    fontFamily: font,
    padding: '6px 12px',
    borderRadius: '6px',
    transition: 'all 0.15s',
  },
  newEvalBtn: {
    width: '100%',
    marginTop: '10px',
    padding: '9px',
    border: `1px solid ${C.brand}`,
    color: C.brand,
    borderRadius: '6px',
    background: 'none',
    fontWeight: '600',
    cursor: 'pointer',
    fontSize: '0.875rem',
    fontFamily: font,
  },
  calcBtn: {
    width: '100%',
    padding: '12px',
    minHeight: '44px',
    backgroundColor: C.brand,
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '0.95rem',
    fontWeight: '700',
    marginTop: '16px',
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '8px',
    fontFamily: font,
    letterSpacing: '0.01em',
  },
  primaryBtn: {
    padding: '9px 20px',
    backgroundColor: C.navy,
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    fontWeight: '600',
    cursor: 'pointer',
    fontSize: '0.875rem',
    fontFamily: font,
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
  },
  actionBtnBlue: {
    padding: '6px 12px',
    backgroundColor: C.navy,
    color: '#fff',
    border: 'none',
    borderRadius: '5px',
    fontSize: '0.8rem',
    cursor: 'pointer',
    fontWeight: '600',
    fontFamily: font,
  },
  actionBtnGray: {
    padding: '6px 12px',
    backgroundColor: C.surface,
    color: C.textSub,
    border: `1px solid ${C.border}`,
    borderRadius: '5px',
    fontSize: '0.8rem',
    cursor: 'pointer',
    fontWeight: '600',
    fontFamily: font,
  },
  actionBtnRed: {
    padding: '6px 12px',
    backgroundColor: C.dangerBg,
    color: C.danger,
    border: `1px solid ${C.dangerBorder}`,
    borderRadius: '5px',
    fontSize: '0.8rem',
    cursor: 'pointer',
    fontWeight: '600',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: font,
  },
  btnMini: {
    padding: '3px 10px',
    fontSize: '0.75rem',
    borderRadius: '4px',
    border: `1px solid ${C.border}`,
    backgroundColor: C.surface,
    color: C.textSub,
    fontWeight: '500',
    cursor: 'pointer',
    fontFamily: font,
  },
  btnMiniActive: {
    padding: '3px 10px',
    fontSize: '0.75rem',
    borderRadius: '4px',
    border: `1px solid ${C.navy}`,
    backgroundColor: C.navy,
    color: '#fff',
    fontWeight: '500',
    cursor: 'pointer',
    fontFamily: font,
  },
  closeBtn: {
    position: 'absolute',
    top: '16px',
    right: '16px',
    fontSize: '20px',
    background: 'none',
    border: 'none',
    color: C.textMuted,
    cursor: 'pointer',
    lineHeight: 1,
    padding: '4px 8px',
    borderRadius: '4px',
  },

  // ─── BADGES ───────────────────────────────────────────────────
  pacienteBadgeStyle: {
    backgroundColor: '#eff6ff',
    color: C.brand,
    padding: '3px 10px',
    borderRadius: '4px',
    fontSize: '0.75rem',
    fontWeight: '600',
    border: `1px solid #bfdbfe`,
    fontFamily: font,
  },
  avatarStyle: {
    width: '40px',
    height: '40px',
    backgroundColor: '#f1f5f9',
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '16px',
  },

  // ─── NAVEGACIÓN ───────────────────────────────────────────────
  rowYesNo: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 0',
    borderBottom: `1px solid ${C.border}`,
  },
  tabActive: {
    padding: '6px 14px',
    borderRadius: '0',
    border: 'none',
    outline: 'none',
    borderBottom: '2px solid #fff',
    backgroundColor: 'transparent',
    color: '#ffffff',
    fontSize: '0.875rem',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontFamily: font,
    transition: 'all 0.15s',
  },
  tabInactive: {
    padding: '6px 14px',
    borderRadius: '0',
    border: 'none',
    outline: 'none',
    borderBottom: '2px solid transparent',
    backgroundColor: 'transparent',
    color: '#94a3b8',
    fontSize: '0.875rem',
    fontWeight: '500',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontFamily: font,
    transition: 'all 0.15s',
  },

  // ─── LOGIN ────────────────────────────────────────────────────
  loginContainer: {
    minHeight: '100vh',
    width: '100vw',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    backgroundColor: C.navy,
    margin: 0,
    padding: '48px 16px',
  },
  loginCard: {
    padding: '40px',
    backgroundColor: C.surface,
    borderRadius: '8px',
    border: `1px solid ${C.border}`,
    width: '100%',
    maxWidth: '440px',
    textAlign: 'left',
    margin: 'auto',
  },
  loginInputGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    border: `1px solid ${C.border}`,
    padding: '9px 12px',
    borderRadius: '6px',
    marginBottom: '10px',
    backgroundColor: C.surface,
    transition: 'border-color 0.15s',
  },
  loginInput: {
    border: 'none',
    outline: 'none',
    width: '100%',
    backgroundColor: 'transparent',
    fontSize: '0.9rem',
    color: C.text,
    fontWeight: '400',
    fontFamily: font,
  },
  loginButton: {
    width: '100%',
    padding: '11px',
    minHeight: '44px',
    backgroundColor: C.navy,
    color: '#ffffff',
    border: 'none',
    borderRadius: '6px',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    fontSize: '0.9rem',
    marginTop: '8px',
    fontFamily: font,
    letterSpacing: '0.01em',
  },
  loginToggleBtn: {
    background: 'none',
    border: 'none',
    outline: 'none',
    color: C.brand,
    marginTop: '20px',
    cursor: 'pointer',
    fontSize: '0.875rem',
    fontWeight: '600',
    fontFamily: font,
    padding: 0,
  },
  loginErrorBox: {
    backgroundColor: C.dangerBg,
    color: C.danger,
    padding: '10px 12px',
    borderRadius: '6px',
    fontSize: '0.85rem',
    fontWeight: '500',
    marginBottom: '12px',
    border: `1px solid ${C.dangerBorder}`,
    fontFamily: font,
  },
  loginSuccessBox: {
    backgroundColor: C.successBg,
    color: C.success,
    padding: '10px 12px',
    borderRadius: '6px',
    fontSize: '0.85rem',
    fontWeight: '500',
    marginBottom: '12px',
    border: `1px solid ${C.successBorder}`,
    fontFamily: font,
  },
};