/*
 * FASS Design System — Clinical Edition
 * Paleta: Slate navy + white, acentos azul oscuro
 * Filosofía: limpio, serio, clínico — sin decoración superflua
 */

const C = {
  bg:        '#f1f5f9',
  surface:   '#ffffff',
  border:    '#e2e8f0',
  borderMd:  '#cbd5e1',
  text:      '#0f172a',
  textSub:   '#475569',
  textMuted: '#94a3b8',
  brand:     '#1d4ed8',
  brandDark: '#1e3a8a',
  danger:    '#b91c1c',
  dangerBg:  '#fef2f2',
  dangerBorder: '#fecaca',
  success:   '#15803d',
  successBg: '#f0fdf4',
  successBorder: '#bbf7d0',
  warning:   '#92400e',
  warningBg: '#fffbeb',
  warningBorder: '#fde68a',
  navy:      '#0f172a',
  navyHover: '#1e293b',
};

const font = '"Inter", system-ui, -apple-system, sans-serif';

const input = {
  width: '100%',
  padding: '9px 12px',
  borderRadius: '6px',
  border: `1px solid ${C.border}`,
  backgroundColor: C.surface,
  color: C.text,
  fontSize: '0.9rem',
  fontFamily: font,
  boxSizing: 'border-box',
  outline: 'none',
  transition: 'border-color 0.15s',
};

export const styles = {

  // ─── TIPOGRAFÍA ───────────────────────────────────────────────
  labelStyle: {
    color: C.text,
    fontSize: '0.8rem',
    fontFamily: font,
    fontWeight: '600',
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
  },
  labelStyleV2: {
    fontSize: '0.75rem',
    fontWeight: '600',
    color: C.textSub,
    marginBottom: '4px',
    fontFamily: font,
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
  },
  subLabel: {
    fontSize: '0.85rem',
    fontWeight: '600',
    color: C.text,
    marginBottom: '8px',
    fontFamily: font,
  },
  subLabelNormal: {
    fontSize: '0.875rem',
    color: C.text,
    fontWeight: '600',
    fontFamily: font,
  },
  secHeader: {
    fontSize: '0.7rem',
    color: C.brand,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    borderBottom: `1px solid ${C.border}`,
    marginBottom: '14px',
    paddingBottom: '6px',
    fontWeight: '700',
    fontFamily: font,
  },

  // ─── INPUTS ───────────────────────────────────────────────────
  inputStyle: { ...input, height: '38px', padding: '0 12px' },
  inputStyleV2: { ...input },
  selectStyle: {
    ...input,
    height: '38px',
    padding: '0 12px',
    cursor: 'pointer',
    appearance: 'none',
  },
  detailInput: {
    ...input,
    marginTop: '8px',
    minHeight: '60px',
    resize: 'vertical',
  },
  searchInput: {
    border: 'none',
    background: 'transparent',
    outline: 'none',
    width: '100%',
    color: C.text,
    fontFamily: font,
    fontSize: '0.9rem',
  },

  // ─── LAYOUT ───────────────────────────────────────────────────
  inputWrapper: { display: 'flex', flexDirection: 'column', gap: '6px', minWidth: '0' },
  calculatorLayout: { display: 'flex', gap: '24px', alignItems: 'flex-start' },
  asideStyle: { width: '380px', flexShrink: '0', position: 'sticky', top: '20px' },
  gridQuestions: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px 24px' },

  // ─── CABECERA ─────────────────────────────────────────────────
  headerStyle: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '0 32px',
    height: '56px',
    backgroundColor: C.navy,
    alignItems: 'center',
    borderBottom: `1px solid #1e293b`,
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },

  // ─── TARJETAS ─────────────────────────────────────────────────
  cardStyle: {
    backgroundColor: C.surface,
    padding: '24px',
    borderRadius: '8px',
    border: `1px solid ${C.border}`,
    marginBottom: '16px',
  },
  optionCard: {
    backgroundColor: C.surface,
    padding: '28px 24px',
    borderRadius: '8px',
    border: `1px solid ${C.border}`,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    transition: 'border-color 0.2s, box-shadow 0.2s',
  },
  cardTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '1rem',
    marginBottom: '16px',
    fontWeight: '700',
    color: C.text,
    fontFamily: font,
  },
  cardHeading: {
    color: C.text,
    fontWeight: '700',
    margin: '0 0 8px 0',
    fontSize: '1.05rem',
    fontFamily: font,
  },
  infoCard: {
    backgroundColor: C.surface,
    padding: '32px',
    borderRadius: '8px',
    border: `1px solid ${C.border}`,
    position: 'relative',
    marginBottom: '16px',
    fontFamily: font,
  },
  questionBlock: {
    padding: '14px',
    backgroundColor: '#fafafa',
    borderRadius: '6px',
    border: `1px solid ${C.border}`,
  },
  emptyCard: {
    padding: '48px',
    textAlign: 'center',
    color: C.textMuted,
    border: `1px dashed ${C.borderMd}`,
    borderRadius: '8px',
    backgroundColor: C.surface,
  },
  itemPacienteStyle: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 16px',
    backgroundColor: '#fafafa',
    borderRadius: '6px',
    border: `1px solid ${C.border}`,
    color: C.text,
    fontFamily: font,
  },
  searchBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    backgroundColor: C.surface,
    padding: '9px 14px',
    borderRadius: '6px',
    border: `1px solid ${C.border}`,
    color: C.text,
  },

  // ─── BOTONES ──────────────────────────────────────────────────
  startBtn: {
    padding: '9px 18px',
    backgroundColor: C.navy,
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.875rem',
    fontFamily: font,
  },
  backBtn: {
    background: 'none',
    border: 'none',
    color: C.brand,
    cursor: 'pointer',
    marginBottom: '12px',
    fontWeight: '600',
    fontSize: '0.875rem',
    fontFamily: font,
    padding: '0',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  logoutBtn: {
    background: 'none',
    border: `1px solid rgba(255,255,255,0.2)`,
    color: '#cbd5e1',
    cursor: 'pointer',
    fontWeight: '500',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '0.85rem',
    fontFamily: font,
    padding: '6px 12px',
    borderRadius: '6px',
    transition: 'all 0.15s',
  },
  newEvalBtn: {
    width: '100%',
    marginTop: '10px',
    padding: '9px',
    border: `1px solid ${C.brand}`,
    color: C.brand,
    borderRadius: '6px',
    background: 'none',
    fontWeight: '600',
    cursor: 'pointer',
    fontSize: '0.875rem',
    fontFamily: font,
  },
  calcBtn: {
    width: '100%',
    padding: '12px',
    backgroundColor: C.brand,
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '0.95rem',
    fontWeight: '700',
    marginTop: '16px',
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '8px',
    fontFamily: font,
    letterSpacing: '0.01em',
  },
  primaryBtn: {
    padding: '9px 20px',
    backgroundColor: C.navy,
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    fontWeight: '600',
    cursor: 'pointer',
    fontSize: '0.875rem',
    fontFamily: font,
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
  },
  actionBtnBlue: {
    padding: '6px 12px',
    backgroundColor: C.navy,
    color: '#fff',
    border: 'none',
    borderRadius: '5px',
    fontSize: '0.8rem',
    cursor: 'pointer',
    fontWeight: '600',
    fontFamily: font,
  },
  actionBtnGray: {
    padding: '6px 12px',
    backgroundColor: C.surface,
    color: C.textSub,
    border: `1px solid ${C.border}`,
    borderRadius: '5px',
    fontSize: '0.8rem',
    cursor: 'pointer',
    fontWeight: '600',
    fontFamily: font,
  },
  actionBtnRed: {
    padding: '6px 12px',
    backgroundColor: C.dangerBg,
    color: C.danger,
    border: `1px solid ${C.dangerBorder}`,
    borderRadius: '5px',
    fontSize: '0.8rem',
    cursor: 'pointer',
    fontWeight: '600',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: font,
  },
  btnMini: {
    padding: '3px 10px',
    fontSize: '0.75rem',
    borderRadius: '4px',
    border: `1px solid ${C.border}`,
    backgroundColor: C.surface,
    color: C.textSub,
    fontWeight: '500',
    cursor: 'pointer',
    fontFamily: font,
  },
  btnMiniActive: {
    padding: '3px 10px',
    fontSize: '0.75rem',
    borderRadius: '4px',
    border: `1px solid ${C.navy}`,
    backgroundColor: C.navy,
    color: '#fff',
    fontWeight: '500',
    cursor: 'pointer',
    fontFamily: font,
  },
  closeBtn: {
    position: 'absolute',
    top: '16px',
    right: '16px',
    fontSize: '20px',
    background: 'none',
    border: 'none',
    color: C.textMuted,
    cursor: 'pointer',
    lineHeight: 1,
    padding: '4px 8px',
    borderRadius: '4px',
  },

  // ─── BADGES ───────────────────────────────────────────────────
  pacienteBadgeStyle: {
    backgroundColor: '#eff6ff',
    color: C.brand,
    padding: '3px 10px',
    borderRadius: '4px',
    fontSize: '0.75rem',
    fontWeight: '600',
    border: `1px solid #bfdbfe`,
    fontFamily: font,
  },
  avatarStyle: {
    width: '40px',
    height: '40px',
    backgroundColor: '#f1f5f9',
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '16px',
  },

  // ─── NAVEGACIÓN ───────────────────────────────────────────────
  rowYesNo: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 0',
    borderBottom: `1px solid ${C.border}`,
  },
  tabActive: {
    padding: '6px 14px',
    borderRadius: '0',
    border: 'none',
    borderBottom: '2px solid #fff',
    backgroundColor: 'transparent',
    color: '#ffffff',
    fontSize: '0.875rem',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontFamily: font,
    transition: 'all 0.15s',
  },
  tabInactive: {
    padding: '6px 14px',
    borderRadius: '0',
    border: 'none',
    borderBottom: '2px solid transparent',
    backgroundColor: 'transparent',
    color: '#94a3b8',
    fontSize: '0.875rem',
    fontWeight: '500',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontFamily: font,
    transition: 'all 0.15s',
  },

  // ─── LOGIN ────────────────────────────────────────────────────
  loginContainer: {
    minHeight: '100vh',
    width: '100vw',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    backgroundColor: C.navy,
    margin: 0,
    padding: '48px 16px',
  },
  loginCard: {
    padding: '40px',
    backgroundColor: C.surface,
    borderRadius: '8px',
    border: `1px solid ${C.border}`,
    width: '100%',
    maxWidth: '440px',
    textAlign: 'left',
    margin: 'auto',
  },
  loginInputGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    border: `1px solid ${C.border}`,
    padding: '9px 12px',
    borderRadius: '6px',
    marginBottom: '10px',
    backgroundColor: C.surface,
    transition: 'border-color 0.15s',
  },
  loginInput: {
    border: 'none',
    outline: 'none',
    width: '100%',
    backgroundColor: 'transparent',
    fontSize: '0.9rem',
    color: C.text,
    fontWeight: '400',
    fontFamily: font,
  },
  loginButton: {
    width: '100%',
    padding: '11px',
    backgroundColor: C.navy,
    color: '#ffffff',
    border: 'none',
    borderRadius: '6px',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    fontSize: '0.9rem',
    marginTop: '8px',
    fontFamily: font,
    letterSpacing: '0.01em',
  },
  loginToggleBtn: {
    background: 'none',
    border: 'none',
    color: C.brand,
    marginTop: '20px',
    cursor: 'pointer',
    fontSize: '0.875rem',
    fontWeight: '600',
    fontFamily: font,
    padding: 0,
  },
  loginErrorBox: {
    backgroundColor: C.dangerBg,
    color: C.danger,
    padding: '10px 12px',
    borderRadius: '6px',
    fontSize: '0.85rem',
    fontWeight: '500',
    marginBottom: '12px',
    border: `1px solid ${C.dangerBorder}`,
    fontFamily: font,
  },
  loginSuccessBox: {
    backgroundColor: C.successBg,
    color: C.success,
    padding: '10px 12px',
    borderRadius: '6px',
    fontSize: '0.85rem',
    fontWeight: '500',
    marginBottom: '12px',
    border: `1px solid ${C.successBorder}`,
    fontFamily: font,
  },
};

    fontSize: '0.95rem',
    fontFamily: '"Inter", sans-serif',
    fontWeight: '600',
  },
  inputStyle: { 
    width: '100%', 
    height: '45px', 
    padding: '0 15px', 
    borderRadius: '10px', 
    border: '1px solid #e2e8f0', 
    backgroundColor: '#f8fafc', 
    color: '#1e293b', 
    fontSize: '0.95rem', 
    fontFamily: '"Inter", sans-serif', 
    boxSizing: 'border-box', 
    outline: 'none' 
  },
  headerStyle: { display: 'flex', justifyContent: 'space-between', padding: '15px 40px', backgroundColor: '#fff', borderBottom: '1px solid #e2e8f0', alignItems: 'center' },
  optionCard: { backgroundColor: '#fff', padding: '40px', borderRadius: '24px', textAlign: 'center', boxShadow: '0 10px 25px rgba(0,0,0,0.05)', display: 'flex', flexDirection: 'column', alignItems: 'center' },
  cardHeading: { color: '#000', fontWeight: '800', margin: '15px 0', fontSize: '1.4rem' },
  avatarStyle: { width: '70px', height: '70px', backgroundColor: '#eff6ff', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '10px' },
  startBtn: { padding: '14px 24px', backgroundColor: '#1e293b', color: '#fff', border: 'none', borderRadius: '12px', cursor: 'pointer', fontWeight: 'bold', width: '100%' },
  cardStyle: { backgroundColor: '#fff', padding: '30px', borderRadius: '20px', boxShadow: '0 2px 10px rgba(0,0,0,0.03)', marginBottom: '20px' },
  backBtn: { background: 'none', border: 'none', color: '#1e293b', cursor: 'pointer', marginBottom: '10px', fontWeight: 'bold' },
  logoutBtn: { background: 'none', border: 'none', color: '#a12121', cursor: 'pointer', fontWeight: 'bold', display: 'flex', alignItems: 'center', gap: '5px' },
  emptyCard: { padding: '50px', textAlign: 'center', color: '#94a3b8', border: '2px dashed #cbd5e1', borderRadius: '20px', backgroundColor: '#fff' },
  newEvalBtn: { width: '100%', marginTop: '10px', padding: '12px', border: '2px solid #2563eb', color: '#2563eb', borderRadius: '12px', background: 'none', fontWeight: 'bold', cursor: 'pointer' },
  calculatorLayout: { display: 'flex', gap: '30px', alignItems: 'flex-start' },
  asideStyle: { width: '400px', flexShrink: '0', position: 'sticky', top: '20px' },
  questionBlock: { padding: '15px', backgroundColor: '#fbfcfd', borderRadius: '12px', border: '1px solid #f1f5f9' },
  gridQuestions: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px 30px' },
  calcBtn: { width: '100%', padding: '18px', backgroundColor: '#2563eb', color: '#fff', border: 'none', borderRadius: '15px', fontSize: '1.1rem', fontWeight: 'bold', marginTop: '20px', cursor: 'pointer', display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '10px' },
  pacienteBadgeStyle: { backgroundColor: '#eff6ff', color: '#2563eb', padding: '5px 15px', borderRadius: '20px', fontSize: '0.8rem', fontWeight: 'bold' },
  rowYesNo: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '8px 0', borderBottom: '1px solid #f1f5f9' },
  subLabelNormal: { fontSize: '0.9rem', color: '#1e293b', fontWeight: '700', fontFamily: '"Inter", sans-serif' },
  
  inputStyleV2: { width: '100%', padding: '12px 15px', borderRadius: '10px', border: '1px solid #e2e8f0', backgroundColor: '#f8fafc', color: '#1e293b', fontSize: '0.95rem', fontFamily: '"Inter", sans-serif', boxSizing: 'border-box', outline: 'none' },
  selectStyle: { 
      width: '100%', 
      height: '45px', 
      padding: '0 15px', 
      borderRadius: '10px', 
      border: '1px solid #e2e8f0', 
      backgroundColor: '#f8fafc', 
      color: '#1e293b', 
      fontSize: '0.95rem', 
      cursor: 'pointer', 
      boxSizing: 'border-box', 
      fontFamily: '"Inter", sans-serif',
      outline: 'none',
    appearance: 'none', 
  },
  labelStyleV2: { fontSize: '0.8rem', fontWeight: '700', color: '#64748b', marginBottom: '4px', fontFamily: '"Inter", sans-serif' },
  
  subLabel: { fontSize: '0.9rem', fontWeight: '700', color: '#1e293b', marginBottom: '10px', fontFamily: '"Inter", sans-serif' },
  secHeader: { fontSize: '0.75rem', color: '#2563eb', textTransform: 'uppercase', borderBottom: '1px solid #eee', marginBottom: '15px', paddingBottom: '5px', fontWeight: '800' },
  inputWrapper: { display: 'flex', flexDirection: 'column', gap: '8px', minWidth: '0' },
  cardTitle: { display: 'flex', alignItems: 'center', gap: '10px', fontSize: '1.2rem', marginBottom: '20px', fontWeight: '800', color: '#000' },
  searchBar: { display: 'flex', alignItems: 'center', gap: '10px', backgroundColor: '#f8fafc', padding: '12px', borderRadius: '12px', border: '1px solid #e2e8f0', color: '#1e293b' },
  searchInput: { border: 'none', background: 'transparent', outline: 'none', width: '100%', color: '#1e293b', fontFamily: '"Inter", sans-serif' },
  itemPacienteStyle: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '15px', backgroundColor: '#f8fafc', borderRadius: '12px', border: '1px solid #e2e8f0', color: '#1e293b', fontFamily: '"Inter", sans-serif' },
  detailInput: { width: '100%', marginTop: '10px', padding: '10px', borderRadius: '8px', border: '1px solid #cbd5e1', backgroundColor: '#fff', color: '#1e293b', fontSize: '0.85rem', fontFamily: '"Inter", sans-serif', minHeight: '60px', resize: 'none', boxSizing: 'border-box' },
  btnMini: { padding: '4px 12px', fontSize: '0.75rem', borderRadius: '6px', border: '1px solid #e2e8f0', backgroundColor: '#fff', color: '#64748b', fontWeight: '400', cursor: 'pointer', fontFamily: '"Inter", sans-serif' },
  btnMiniActive: { padding: '4px 12px', fontSize: '0.75rem', borderRadius: '6px', border: '1px solid #1e293b', backgroundColor: '#1e293b', color: '#fff', borderColor: '#1e293b', fontWeight: '400', cursor: 'pointer', fontFamily: '"Inter", sans-serif' },
  actionBtnBlue: { padding: '8px 12px', backgroundColor: '#1e293b', color: '#fff', border: 'none', borderRadius: '8px', fontSize: '0.8rem', cursor: 'pointer', fontWeight: '600' },
  actionBtnGray: { padding: '8px 12px', backgroundColor: '#f1f5f9', color: '#475569', border: '1px solid #e2e8f0', borderRadius: '8px', fontSize: '0.8rem', cursor: 'pointer', fontWeight: '600' },
  actionBtnRed: { padding: '8px 12px', backgroundColor: '#fef2f2', color: '#dc2626', border: '1px solid #fee2e2', borderRadius: '8px', fontSize: '0.8rem', cursor: 'pointer', fontWeight: '600', display: 'flex', alignItems: 'center', justifyContent: 'center' },

  // --- MÓDULO LOGIN ---
  loginContainer: { 
    minHeight: '100vh', width: '100vw', display: 'flex', 
    justifyContent: 'center', alignItems: 'flex-start', 
    backgroundColor: '#f1f5f9', margin: 0, padding: '30px 0' 
  },
  loginCard: { 
    padding: '40px 36px', backgroundColor: '#ffffff', borderRadius: '28px', 
    boxShadow: '0 25px 50px -12px rgba(0,0,0,0.1)', width: '100%', 
    maxWidth: '460px', textAlign: 'center', border: '1px solid #e2e8f0',
    margin: 'auto'
  },
  loginInputGroup: { 
    display: 'flex', alignItems: 'center', gap: '12px', 
    border: '2px solid #e2e8f0', padding: '11px 16px', 
    borderRadius: '14px', marginBottom: '12px', backgroundColor: '#f8fafc' 
  },
  loginInput: { 
    border: 'none', outline: 'none', width: '100%', 
    backgroundColor: 'transparent', fontSize: '1rem', 
    color: '#1e293b', fontWeight: '500', fontFamily: '"Inter", sans-serif' 
  },
  loginButton: { 
    width: '100%', padding: '16px', backgroundColor: '#1e293b', 
    color: '#ffffff', border: 'none', borderRadius: '16px', 
    fontWeight: '800', cursor: 'pointer', display: 'flex', 
    alignItems: 'center', justifyContent: 'center', gap: '10px', 
    fontSize: '1.1rem', boxShadow: '0 10px 15px -3px rgba(37, 99, 235, 0.3)', 
    marginTop: '10px', fontFamily: '"Inter", sans-serif' 
  },
  loginToggleBtn: { 
    background: 'none', border: 'none', color: '#1e293b', 
    marginTop: '25px', cursor: 'pointer', fontSize: '0.95rem', 
    fontWeight: '700', textDecoration: 'underline', fontFamily: '"Inter", sans-serif' 
  },
  loginErrorBox: { 
    backgroundColor: '#fff1f2', color: '#be123c', padding: '12px', 
    borderRadius: '12px', fontSize: '0.9rem', fontWeight: '600', 
    marginBottom: '20px', border: '1px solid #fecdd3' 
  },
  loginSuccessBox: { 
    backgroundColor: '#f0fdf4', color: '#16a34a', padding: '12px', 
    borderRadius: '12px', fontSize: '0.9rem', fontWeight: '600', 
    marginBottom: '20px', border: '1px solid #bbf7d0' 
  },

  tabInactive: {
    padding: '8px 16px',
    borderRadius: '10px',
    border: 'none',
    backgroundColor: 'transparent',
    color: '#64748b',
    fontSize: '0.9rem',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    transition: 'all 0.2s',
    fontFamily: '"Inter", sans-serif'
  },
  tabActive: {
    padding: '8px 16px',
    borderRadius: '10px',
    border: 'none',
    backgroundColor: '#ffffff',
    color: '#1e293b',
    fontSize: '0.9rem',
    fontWeight: '700',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
    fontFamily: '"Inter", sans-serif'
  },

  // --- TARJETA DE INFORMACIÓN (MODAL/INFO) ---
  infoCard: {
    backgroundColor: '#ffffff',
    padding: '40px',
    borderRadius: '20px',
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
    border: '1px solid #e2e8f0',
    position: 'relative',
    animation: 'fadeIn 0.3s ease',
    marginBottom: '20px',
    fontFamily: '"Inter", sans-serif'
  },
  closeBtn: {
    position: 'absolute',
    top: '20px',
    right: '20px',
    fontSize: '24px',
    background: 'none',
    border: 'none',
    color: '#94a3b8',
    cursor: 'pointer',
    lineHeight: 1
  }
};